# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_book.proto\x12\x04MARS\"\xa9\x03\n\x05\x41gent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1b\n\x05shape\x18\x02 \x01(\x0b\x32\x0c.MARS.Vector\x12%\n\x0flinear_velocity\x18\x03 \x01(\x0b\x32\x0c.MARS.Vector\x12\x18\n\x10\x61ngular_velocity\x18\x04 \x01(\x02\x12\r\n\x05\x61ngle\x18\x05 \x01(\x02\x12\x1d\n\x08position\x18\x06 \x01(\x0b\x32\x0b.MARS.Point\x12)\n\x14\x64\x65stination_location\x18\x07 \x01(\x0b\x32\x0b.MARS.Point\x12)\n\rlocal_planner\x18\x08 \x01(\x0b\x32\x12.MARS.LocalPlanner\x12+\n\x0eglobal_planner\x18\t \x01(\x0b\x32\x13.MARS.GlobalPlanner\x12\x1c\n\x06sensor\x18\n \x01(\x0b\x32\x0c.MARS.Sensor\x12\x17\n\x0fray_length_list\x18\x0b \x03(\x02\x12&\n\x11sequence_of_poses\x18\x0c \x03(\x0b\x32\x0b.MARS.Point\x12&\n\x11internal_stations\x18\r \x03(\x0b\x32\x0b.MARS.Point\"\x1c\n\x0cLocalPlanner\x12\x0c\n\x04type\x18\x01 \x01(\t\"\x84\x01\n\rGlobalPlanner\x12\x0c\n\x04type\x18\x01 \x01(\t\x12-\n\x08map_type\x18\x02 \x01(\x0e\x32\x1b.MARS.GlobalPlanner.MapType\x12\x11\n\tagents_id\x18\x03 \x03(\x05\"#\n\x07MapType\x12\x08\n\x04GRID\x10\x00\x12\x0e\n\nCONTINUOUS\x10\x01\"\x98\x01\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06radius\x18\x02 \x01(\x02\x12\r\n\x05\x61ngle\x18\x03 \x01(\x02\x12\x1d\n\x08location\x18\x04 \x01(\x0b\x32\x0b.MARS.Point\x12\x19\n\x11visible_agents_id\x18\x05 \x03(\x05\x12)\n\x11visible_obstacles\x18\x06 \x03(\x0b\x32\x0e.MARS.Obstacle\"V\n\x08Obstacle\x12\x1b\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x0b.MARS.Point\x12\x1f\n\tdimension\x18\x02 \x01(\x0b\x32\x0c.MARS.Vector\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x1e\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENT']._serialized_start=26
  _globals['_AGENT']._serialized_end=451
  _globals['_LOCALPLANNER']._serialized_start=453
  _globals['_LOCALPLANNER']._serialized_end=481
  _globals['_GLOBALPLANNER']._serialized_start=484
  _globals['_GLOBALPLANNER']._serialized_end=616
  _globals['_GLOBALPLANNER_MAPTYPE']._serialized_start=581
  _globals['_GLOBALPLANNER_MAPTYPE']._serialized_end=616
  _globals['_SENSOR']._serialized_start=619
  _globals['_SENSOR']._serialized_end=771
  _globals['_OBSTACLE']._serialized_start=773
  _globals['_OBSTACLE']._serialized_end=859
  _globals['_POINT']._serialized_start=861
  _globals['_POINT']._serialized_end=890
  _globals['_VECTOR']._serialized_start=892
  _globals['_VECTOR']._serialized_end=922
# @@protoc_insertion_point(module_scope)
